version: '3'
services: 
  mysql:
    image: mysql:8.0.25
    restart: always
    container_name: mysql-server.host
    volumes:
      - ./docker/data/mysqldata:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./docker/init/mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=aiserver"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

  redis:
    image: redis:6.2.5
    restart: always
    container_name: redis-server.host
    ports:
      - 6379:6379
    volumes: 
      - ./docker/data/redsidata:/data
    command: redis-server --port 6379 --requirepass 123456 --appendonly yes

  aidea-server:
    image: registry.cn-hangzhou.aliyuncs.com/18join/aidea-server:1.0.4
    restart: always
    container_name: aidea-server
    depends_on:
      - mysql
    volumes:
      - ./docker/config/config.yaml:/etc/aidea.yaml
      - ./docker/config/apple-key.p8:/etc/apple-key.p8
      - ./docker/data/serverdata:/data
    ports:
      - 8080:8080

